/**
 * Script to create test patient accounts
 * 
 * Usage:
 *   pnpm run create-patients -- --count 5
 */

import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import { User, GeneratedCredential, PatientProfile } from '../models';

// Load environment variables
dotenv.config();

interface PatientData {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
}

// Sample patient data
const samplePatients: Omit<PatientData, 'password'>[] = [
  { firstName: 'John', lastName: 'Smith', email: 'john.smith@example.com' },
  { firstName: 'Sarah', lastName: 'Johnson', email: 'sarah.johnson@example.com' },
  { firstName: 'Michael', lastName: 'Williams', email: 'michael.williams@example.com' },
  { firstName: 'Emily', lastName: 'Brown', email: 'emily.brown@example.com' },
  { firstName: 'David', lastName: 'Jones', email: 'david.jones@example.com' },
  { firstName: 'Jessica', lastName: 'Davis', email: 'jessica.davis@example.com' },
  { firstName: 'Robert', lastName: 'Miller', email: 'robert.miller@example.com' },
  { firstName: 'Amanda', lastName: 'Wilson', email: 'amanda.wilson@example.com' },
  { firstName: 'James', lastName: 'Moore', email: 'james.moore@example.com' },
  { firstName: 'Ashley', lastName: 'Taylor', email: 'ashley.taylor@example.com' },
];

/**
 * Generate a random password
 */
function generatePassword(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%';
  let password = '';
  for (let i = 0; i < 12; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
}

/**
 * Create patients
 */
async function createPatients(count: number): Promise<void> {
  const createdPatients: { email: string; password: string; name: string }[] = [];
  
  console.log(`\n👥 Creating ${count} patient account(s)...\n`);
  
  for (let i = 0; i < count; i++) {
    const patientData = samplePatients[i % samplePatients.length];
    const password = generatePassword();
    
    // Make email unique if we're creating more than sample data allows
    const emailSuffix = i >= samplePatients.length ? `${Math.floor(i / samplePatients.length)}` : '';
    const email = emailSuffix 
      ? patientData.email.replace('@', `${emailSuffix}@`)
      : patientData.email;
    
    try {
      // Check if user already exists
      const existingUser = await User.findOne({ email });
      if (existingUser) {
        console.log(`  ⚠️  ${email} already exists, skipping...`);
        continue;
      }
      
      // Hash password
      const hashedPassword = await bcrypt.hash(password, 12);
      
      // Create user
      const user = new User({
        email,
        password: hashedPassword,
        firstName: patientData.firstName,
        lastName: patientData.lastName,
        role: 'patient',
        status: 'active',
        emailVerified: true,
      });
      
      await user.save();
      
      // Create patient profile
      const patientProfile = new PatientProfile({
        userId: user._id,
        gender: ['male', 'female'][Math.floor(Math.random() * 2)] as 'male' | 'female',
        dateOfBirth: new Date(Date.now() - (20 + Math.floor(Math.random() * 40)) * 365 * 24 * 60 * 60 * 1000),
        bloodType: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'][Math.floor(Math.random() * 8)],
        phone: `+1-555-${String(Math.floor(Math.random() * 10000000)).padStart(7, '0')}`,
        address: {
          city: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'][Math.floor(Math.random() * 5)],
          state: ['NY', 'CA', 'IL', 'TX', 'AZ'][Math.floor(Math.random() * 5)],
          country: 'USA',
        },
        medicalHistory: {
          familyHistory: Math.random() > 0.7,
          consanguinity: Math.random() > 0.9,
          chronicConditions: [],
          allergies: [],
          medications: [],
        },
      });
      
      await patientProfile.save();
      
      // Store credentials in database
      const credential = new GeneratedCredential({
        userId: user._id,
        email,
        password, // Store plain text for test accounts
        role: 'patient',
        firstName: patientData.firstName,
        lastName: patientData.lastName,
        notes: 'Generated by create-patients script',
      });
      await credential.save();
      
      createdPatients.push({
        email,
        password,
        name: `${patientData.firstName} ${patientData.lastName}`,
      });
      
      console.log(`  ✅ Created: ${patientData.firstName} ${patientData.lastName} (+ PatientProfile)`);
      
    } catch (error) {
      console.error(`  ❌ Failed to create ${email}: ${(error as Error).message}`);
    }
  }
  
  // Print credentials summary
  if (createdPatients.length > 0) {
    console.log('\n' + '='.repeat(70));
    console.log('🔐 PATIENT CREDENTIALS (Save these before they\'re gone!)');
    console.log('='.repeat(70));
    console.log('\n%-35s %-20s %s'.replace('%s', 'EMAIL').replace('%s', 'PASSWORD').replace('%s', 'NAME'));
    console.log('-'.repeat(70));
    
    for (const patient of createdPatients) {
      console.log(`${patient.email.padEnd(35)} ${patient.password.padEnd(20)} ${patient.name}`);
    }
    
    console.log('\n' + '='.repeat(70));
    console.log(`Total created: ${createdPatients.length} patient(s)`);
    console.log('='.repeat(70) + '\n');
  }
}

/**
 * Parse command line arguments
 */
function parseArgs(): number {
  const args = process.argv.slice(2);
  let count = 5;
  
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--count' || args[i] === '-c') {
      count = parseInt(args[++i], 10);
      if (isNaN(count) || count < 1) {
        console.error('Invalid count. Must be a positive number.');
        process.exit(1);
      }
    }
    if (args[i] === '--help' || args[i] === '-h') {
      console.log(`
Create Patients Script
======================

Usage:
  pnpm run create-patients -- [options]

Options:
  -c, --count <number>   Number of patients to create (default: 5)
  -h, --help             Show this help message
`);
      process.exit(0);
    }
  }
  
  return count;
}

/**
 * Main function
 */
async function main(): Promise<void> {
  const count = parseArgs();
  
  console.log('\n🏥 Patient Account Creator');
  console.log('==========================\n');
  
  // Connect to MongoDB
  const mongoUri = process.env.MONGODB_URI;
  if (!mongoUri) {
    console.error('❌ MONGODB_URI environment variable is not set');
    process.exit(1);
  }
  
  try {
    console.log('📡 Connecting to MongoDB...');
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB');
    
    // Create patients
    await createPatients(count);
    
  } catch (error) {
    console.error('❌ Error:', (error as Error).message);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('📡 Disconnected from MongoDB');
  }
}

// Run the script
main();
